version: "3"  # version of docker-compose

volumes:
  postgres_volume:  # volume where data will be stored

services:
  bot:
    build: .  # where Dockerfile of this service is placed
    restart: always  # should docker restart app when VM reboots
    links:
      - dbpostgres
    depends_on:
      - dbpostgres

  dbpostgres:
    image: postgres:latest
    restart: always
    environment:  # environmental variables, can be loaded from .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_volume:/var/lib/postgresql/data  # default path postgres saves data in
    ports:
      - "5432:5432"
